CREATE TABLE `affiliateNodes` (
`id` int AUTO_INCREMENT NOT NULL,
`userId` int NOT NULL,
`brandName` varchar(255) NOT NULL,
`slug` varchar(255) NOT NULL,
`destination` text NOT NULL,
`platform` varchar(64) NOT NULL,
`category` varchar(128) NOT NULL,
`status` enum('active','paused','alert') NOT NULL DEFAULT 'active',
`clicks` varchar(32) NOT NULL DEFAULT '0',
`earnings` varchar(32) NOT NULL DEFAULT '$0',
`commission` varchar(128) NOT NULL DEFAULT 'TBD',
`complianceDisclosure` text,
`complianceRulesJson` text,
`complianceStatus` enum('passed','warning','failed') NOT NULL DEFAULT 'passed',
`complianceFtcNotes` text,
`keywordResearchJson` text,
`marketingAngle` text,
`personasJson` text,
`contentSuggestionsJson` text,
`targetPlatformsJson` text,
`strategyNotes` text,
`createdAt` timestamp NOT NULL DEFAULT (now()),
`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT `affiliateNodes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `nodeAssets` (
`id` int AUTO_INCREMENT NOT NULL,
`nodeId` int NOT NULL,
`userId` int NOT NULL,
`filename` varchar(512) NOT NULL,
`originalName` varchar(512) NOT NULL,
`mimeType` varchar(128) NOT NULL,
`fileSize` int NOT NULL,
`s3Key` varchar(1024) NOT NULL,
`url` text NOT NULL,
`assetType` enum('image','banner','copy','video','document','other') NOT NULL DEFAULT 'other',
`label` varchar(255),
`createdAt` timestamp NOT NULL DEFAULT (now()),
CONSTRAINT `nodeAssets_id` PRIMARY KEY(`id`)
);
